### Article Like
GET localhost:8080/api/v1/article_like/like/50f8cc76-2616-4586-8711-76ab2640d1dc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNTEwNTEsImlkIjoxOCwicm9sZSI6IlVTRVIiLCJleHAiOjE2ODM0Mzc0NTEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.DbWYWx0X8g7TzfpRJFCJv78HRzCnPcKNowQnwwm9MXLbatJuPKbUUpppW-6ZUcncfH8h2i5oCPDMr3oB7ndpww


### Article Dislike
GET localhost:8080/api/v1/article_like/dislike/50f8cc76-2616-4586-8711-76ab2640d1dc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNTEwNTEsImlkIjoxOCwicm9sZSI6IlVTRVIiLCJleHAiOjE2ODM0Mzc0NTEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.DbWYWx0X8g7TzfpRJFCJv78HRzCnPcKNowQnwwm9MXLbatJuPKbUUpppW-6ZUcncfH8h2i5oCPDMr3oB7ndpww


### Article Delete
GET localhost:8080/api/v1/article_like/delete/50f8cc76-2616-4586-8711-76ab2640d1dc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNTEwNTEsImlkIjoxOCwicm9sZSI6IlVTRVIiLCJleHAiOjE2ODM0Mzc0NTEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.DbWYWx0X8g7TzfpRJFCJv78HRzCnPcKNowQnwwm9MXLbatJuPKbUUpppW-6ZUcncfH8h2i5oCPDMr3oB7ndpww
