### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "admin@mail.ru",
  "password": "12345"
}


### Registration
POST localhost:8080/api/v1/auth/registration
Content-Type:  application/json

{
  "name": "User",
  "surname": "Userov",
  "email": "user1@mail.ru",
  "phone": "12345",
  "password": "123"
}