### Create category
POST localhost:8080/api/v1/category
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNjcwMDIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODM0NTM0MDIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9._sWh6QVN8ERHPgWnyMFDg6k-t6gtLI4y4GVRJiDUN2NYdrSWQqZAdyWsW09H3Ji3ks0G1AWsFrMSgQoShwV0Mw
Content-Type:  application/json

{
  "nameUZ": "Yoshlik1",
  "nameRU": "Yoshlik2",
  "nameEN": "Yoshlik3"
}



### Update cateory
PUT localhost:8080/api/v1/category/update/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5MjAxNTIsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMwMDY1NTIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.CF8knCdnvSd3ab8LN46_R-6MQq0tad0WwHkqClW4UIfXR_QrTbFs3Jnl6xUblMOKSRXZ52DuMKWPpQLqWuCqcA
Content-Type:  application/json

{
  "nameUZ": "Samarqand",
  "nameRU": "Самарканд",
  "nameEN": "Samarkand"
}


### Delete category byId
DELETE localhost:8080/api/v1/category/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5MjAxNTIsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMwMDY1NTIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.CF8knCdnvSd3ab8LN46_R-6MQq0tad0WwHkqClW4UIfXR_QrTbFs3Jnl6xUblMOKSRXZ52DuMKWPpQLqWuCqcA


### Category List
GET localhost:8080/api/v1/category/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5MjAxNTIsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMwMDY1NTIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.CF8knCdnvSd3ab8LN46_R-6MQq0tad0WwHkqClW4UIfXR_QrTbFs3Jnl6xUblMOKSRXZ52DuMKWPpQLqWuCqcA


### Get cateory langName
PUT localhost:8080/api/v1/category//getByLang/nameUZ

