### Comment Like
GET localhost:8080/api/v1/article_like/like/0432d05a-e239-48b5-8a53-6954eaf32846
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNzg1OTAsImlkIjo4LCJyb2xlIjoiVVNFUiIsImV4cCI6MTY4MzQ2NDk5MCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.XSTf1nBJoKsc0EnVZ1RmwJLqd2yJn4s_kJ5LasGMwCRaP7jKTvgft7GticOLJFZn4r05NizxW8BUTqe6-bOBjw



### Comment Dislike
GET localhost:8080/api/v1/article_like/dislike/0432d05a-e239-48b5-8a53-6954eaf32846
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNzg1OTAsImlkIjo4LCJyb2xlIjoiVVNFUiIsImV4cCI6MTY4MzQ2NDk5MCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.XSTf1nBJoKsc0EnVZ1RmwJLqd2yJn4s_kJ5LasGMwCRaP7jKTvgft7GticOLJFZn4r05NizxW8BUTqe6-bOBjw


### Comment Delete
GET localhost:8080/api/v1/article_like/delete/0432d05a-e239-48b5-8a53-6954eaf32846
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNzg1OTAsImlkIjo4LCJyb2xlIjoiVVNFUiIsImV4cCI6MTY4MzQ2NDk5MCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.XSTf1nBJoKsc0EnVZ1RmwJLqd2yJn4s_kJ5LasGMwCRaP7jKTvgft7GticOLJFZn4r05NizxW8BUTqe6-bOBjw
