
### Create comment
POST localhost:8080/api/v1/comment/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNzQ5OTMsImlkIjo4LCJyb2xlIjoiVVNFUiIsImV4cCI6MTY4MzQ2MTM5MywiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.qUQVWK158KWZwhklETGbb9Fnsac-Jm97xEssNYFcj--RD-ZC52KjVVprzGlQYLWsJSXqF2fUQ4dn_so1WIX6DA
Content-Type:  application/json

{
  "content": "Salom4",
  "articleId": "2db26b85-74fd-436d-a83c-8cbba6aca005",
  "replayId": null
}

### Update comment
PUT localhost:8080/api/v1/comment/update/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNTEwNTEsImlkIjoxOCwicm9sZSI6IlVTRVIiLCJleHAiOjE2ODM0Mzc0NTEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.DbWYWx0X8g7TzfpRJFCJv78HRzCnPcKNowQnwwm9MXLbatJuPKbUUpppW-6ZUcncfH8h2i5oCPDMr3oB7ndpww
Content-Type:  application/json

{
  "content": "Alisher Usmonovning o'g'li bor ekan2",
  "articleId": "bb596bab-8788-45b5-85d4-90c2d3b9c08e"
}


### Delete comment byId
DELETE localhost:8080/api/v1/comment/delete/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNTEwNTEsImlkIjoxOCwicm9sZSI6IlVTRVIiLCJleHAiOjE2ODM0Mzc0NTEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.DbWYWx0X8g7TzfpRJFCJv78HRzCnPcKNowQnwwm9MXLbatJuPKbUUpppW-6ZUcncfH8h2i5oCPDMr3oB7ndpww


### Comment List By article
GET localhost:8080/api/v1/comment/list/2db26b85-74fd-436d-a83c-8cbba6aca005


### Comment List Pagination
GET localhost:8080/api/v1/comment/list-all-paging?page=1&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNjcwMDIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODM0NTM0MDIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9._sWh6QVN8ERHPgWnyMFDg6k-t6gtLI4y4GVRJiDUN2NYdrSWQqZAdyWsW09H3Ji3ks0G1AWsFrMSgQoShwV0Mw


