
### Create comment
POST localhost:8080/api/v1/comment/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMyMDA0NDQsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMyODY4NDQsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.vETe_l5ViMyKbHghl04VFkvHy4ZmtIXeSbPkTqtFqGjwU69KE9namzT1xemGygOQ4SEfEhGXyuF5HcGx_nMeog
Content-Type:  application/json

{
  "content": "Salom4",
  "articleId": "bb596bab-8788-45b5-85d4-90c2d3b9c08e",
  "replayId": null
}

### Update comment
PUT localhost:8080/api/v1/comment/update/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMyMDA0NDQsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMyODY4NDQsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.vETe_l5ViMyKbHghl04VFkvHy4ZmtIXeSbPkTqtFqGjwU69KE9namzT1xemGygOQ4SEfEhGXyuF5HcGx_nMeog
Content-Type:  application/json

{
  "content": "Alisher Usmonovning o'g'li bor ekan2",
  "articleId": "dcc2fcfc-286c-4752-a04d-c6f84597a657"
}


### Delete comment byId
DELETE localhost:8080/api/v1/comment/delete/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5MjAxNTIsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMwMDY1NTIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.CF8knCdnvSd3ab8LN46_R-6MQq0tad0WwHkqClW4UIfXR_QrTbFs3Jnl6xUblMOKSRXZ52DuMKWPpQLqWuCqcA


### Region List
GET localhost:8080/api/v1/comment/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5MjAxNTIsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMwMDY1NTIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.CF8knCdnvSd3ab8LN46_R-6MQq0tad0WwHkqClW4UIfXR_QrTbFs3Jnl6xUblMOKSRXZ52DuMKWPpQLqWuCqcA


