### Create profle
POST localhost:8080/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI1OTAzMTYsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI2NzY3MTYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1hOMfV-OMesPyjjy5ZRDLOWvheGlsPDlCLbZTqTFVowi1_C-Z-2cZt6Mudr0YeDoi4qFCMwsQDpnpGXJfnEYwQ
Content-Type:  application/json

{
  "name": "Alish",
  "surname": "Aliyev",
  "email": "ali@mail.ru",
  "phone": "12345",
  "password": "123",
  "role": "MODERATOR"
}